/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodRouteImport } from './routes/method'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as SamplesIdRouteImport } from './routes/samples.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesIdRoute = SamplesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SamplesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/samples': typeof SamplesRouteWithChildren
  '/samples/$id': typeof SamplesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/samples': typeof SamplesRouteWithChildren
  '/samples/$id': typeof SamplesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/samples': typeof SamplesRouteWithChildren
  '/samples/$id': typeof SamplesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/method' | '/samples' | '/samples/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/method' | '/samples' | '/samples/$id'
  id: '__root__' | '/' | '/method' | '/samples' | '/samples/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodRoute: typeof MethodRoute
  SamplesRoute: typeof SamplesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$id': {
      id: '/samples/$id'
      path: '/$id'
      fullPath: '/samples/$id'
      preLoaderRoute: typeof SamplesIdRouteImport
      parentRoute: typeof SamplesRoute
    }
  }
}

interface SamplesRouteChildren {
  SamplesIdRoute: typeof SamplesIdRoute
}

const SamplesRouteChildren: SamplesRouteChildren = {
  SamplesIdRoute: SamplesIdRoute,
}

const SamplesRouteWithChildren =
  SamplesRoute._addFileChildren(SamplesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodRoute: MethodRoute,
  SamplesRoute: SamplesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
